### ISSUE TITLE
Week calculation is wrong

### ISSUE THREAD

**Issue by joaocbatista** [djs2014/whattired#5]
The week totals are reset mid week.

Looking at the code, it seems the function getWeekNumber is calculating the wrong week number. It's using the last day of the previous year, getting the number of seconds from today until that day, then dividing by the number of seconds in a week.

The problem with this, is that depending on which day of week is the last day of the previous year, then the day of week that the week odometer is reset changes, instead of using always Monday, as expected.

After a search on garmin connect iq forums, found this that might be helpful: https://forums.garmin.com/developer/connect-iq/f/discussion/2778/week-of-year/27615#27615. Copying all 3 functions and using the iso_week_number function should do the trick.

Let me know if I can help somehow.

**Comment by joaocbatista** [comment]
I've made some changes and tested it, seems to be working fine locally to me. Feel free to incorporate this in your project, I've created a fork here: https://github.com/joaocbatista/whattired

**Comment by djs2014** [comment]
Thanks João,
I used thosed functions to calculate the weeknr (and looked at your code).
Uploaded new version
